# Generated by Django 4.2.8 on 2024-01-02 02:24

import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('heads', models.IntegerField(default=None, null=True)),
                ('image', image_cropping.fields.ImageCropField(blank=True, upload_to='shapes')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('n', models.CharField(blank=True, max_length=255)),
                ('ne', models.CharField(blank=True, max_length=255)),
                ('e', models.CharField(blank=True, max_length=255)),
                ('se', models.CharField(blank=True, max_length=255)),
                ('s', models.CharField(blank=True, max_length=255)),
                ('sw', models.CharField(blank=True, max_length=255)),
                ('w', models.CharField(blank=True, max_length=255)),
                ('nw', models.CharField(blank=True, max_length=255)),
                ('image', image_cropping.fields.ImageCropField(blank=True, upload_to='uploaded_images')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '500x500', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping')),
                ('shape', models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='core.shape')),
            ],
            options={
                'ordering': ('shape', 'num'),
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.IntegerField()),
                ('r', models.IntegerField()),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.piece')),
                ('shape', models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='core.shape')),
                ('turns', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
