# Generated by Django 4.2.8 on 2023-12-29 15:10

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('n', models.CharField(blank=True, max_length=255)),
                ('ne', models.CharField(blank=True, max_length=255)),
                ('e', models.CharField(blank=True, max_length=255)),
                ('se', models.CharField(blank=True, max_length=255)),
                ('s', models.CharField(blank=True, max_length=255)),
                ('sw', models.CharField(blank=True, max_length=255)),
                ('w', models.CharField(blank=True, max_length=255)),
                ('nw', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='uploaded_images')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '500x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
        ),
    ]
