# Generated by Django 4.2.8 on 2023-12-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_alter_piece_cropping_alter_piece_image_imagefk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefk',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageFK',
        ),
    ]
