# Generated by Django 4.2.8 on 2023-12-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='heads',
            field=models.IntegerField(default=0),
        ),
    ]
