# Generated by Django 4.2.8 on 2023-12-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_piece_heads'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='style',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
