# Generated by Django 4.2.8 on 2023-12-31 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_shape_cropping_alter_shape_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='shape',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shape'),
        ),
    ]
