# Generated by Django 4.2.8 on 2023-12-31 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_piece_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shape'),
        ),
    ]
