# Generated by Django 4.2.8 on 2023-12-31 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_piece_options_rename_x_piece_ord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ('shape', 'num')},
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='ord',
            new_name='num',
        ),
    ]
