# Generated by Django 4.2.8 on 2023-12-31 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_piece_heads_remove_piece_style_cell_turns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='x',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='cell',
            old_name='y',
            new_name='r',
        ),
    ]
